import { ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Panel } from '@/components/ui/panel';
import { requireAdminPageSession } from '@/lib/admin-page-session';
import { DEFAULT_AWS_REGION, DEFAULT_TIMEZONE } from '@/lib/delivery/types';

const checks = ['Admin login required before exposing delivery data', 'Raw customer CSV files stay out of git history', 'NEXT_PUBLIC_GOOGLE_MAPS_API_KEY uses HTTP referrer restrictions', 'Server Google Maps keys use server/IP restrictions', 'AWS target region is Canada Central, not Seoul', 'Address/coordinate data is minimized in logs'];
export default async function SettingsPage() { await requireAdminPageSession('/settings'); return <main className="min-h-screen px-5 py-5 lg:px-8"><section className="mx-auto max-w-5xl"><Button asChild variant="subtle" size="sm"><Link href="/"><ArrowLeft size={14}/> Dashboard</Link></Button><h1 className="mt-5 text-4xl font-[510] tracking-[-1.056px]">Operations settings</h1><p className="mt-2 text-sm text-[var(--text-tertiary)]">MVP defaults and deployment guardrails for Tomotono delivery operations.</p><div className="mt-6 grid gap-4 md:grid-cols-2"><Panel className="p-5"><h2 className="font-[510]">Environment</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-[var(--text-tertiary)]">Timezone</dt><dd>{DEFAULT_TIMEZONE}</dd></div><div className="flex justify-between"><dt className="text-[var(--text-tertiary)]">AWS region</dt><dd>{DEFAULT_AWS_REGION}</dd></div><div className="flex justify-between"><dt className="text-[var(--text-tertiary)]">Maps browser key</dt><dd>{process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY ? 'configured' : 'missing'}</dd></div></dl></Panel><Panel className="p-5"><h2 className="font-[510]">Security checklist</h2><ul className="mt-4 space-y-2 text-sm text-[var(--text-tertiary)]">{checks.map((check) => <li key={check} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 rounded-full bg-[var(--success)]" />{check}</li>)}</ul></Panel></div></section></main>; }
